apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: aegis-allow-airflow-to-minio
  namespace: aegis-data
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: minio
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: aegis-airflow
      ports:
        - protocol: TCP
          port: 9000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: aegis-allow-airflow-to-mlflow
  namespace: aegis-ml
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: mlflow
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: aegis-airflow
      ports:
        - protocol: TCP
          port: 5000
