apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: aegis-fraud-baseline
  namespace: aegis-serving-dev
  labels:
    app.kubernetes.io/part-of: aegis
    aegis.io/phase: "7"
    aegis.io/environment: dev
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
    serving.kserve.io/secretName: aegis-model-storage
    aegis.io/runtime-revision: "phase7-v2"
spec:
  predictor:
    serviceAccountName: aegis-inference
    minReplicas: 1
    maxReplicas: 2

    model:
      modelFormat:
        name: mlflow
        version: "2"

      runtime: aegis-mlflow-runtime
      protocolVersion: v2

      storageUri: s3://aegis-mlflow-artifacts/3/62671fa607a0479d8c2fcc98ddb05256/artifacts/model

      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: "1"
          memory: 2Gi
