apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - aegis-mlflow-runtime.yaml
  - aegis-fraud-baseline.yaml
  - aegis-fraud-baseline-metrics-service.yaml
  - aegis-fraud-baseline-servicemonitor.yaml
  - aegis-allow-metoro-mlserver-metrics.yaml
  - aegis-fraud-baseline-dashboard.yaml
