apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces/aegis-namespaces.yaml
  - quotas/aegis-resourcequotas.yaml
  - limitranges/aegis-limitranges.yaml
  - rbac/aegis-serviceaccounts.yaml
  - rbac/aegis-basic-rbac.yaml
  - networkpolicies/aegis-default-deny-ingress.yaml
