apiVersion: v1
kind: ServiceAccount
metadata:
  name: aegis-platform-admin
  namespace: aegis-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aegis-airflow
  namespace: aegis-airflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aegis-mlflow
  namespace: aegis-ml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aegis-training
  namespace: aegis-ml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aegis-feast
  namespace: aegis-features
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aegis-valkey
  namespace: aegis-features
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aegis-stream-processor
  namespace: aegis-data
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aegis-inference
  namespace: aegis-serving-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aegis-inference
  namespace: aegis-serving-prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aegis-monitoring-reader
  namespace: aegis-monitoring
