apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- mlflow-postgres.yaml
- mlflow-deployment.yaml
- mlflow-services.yaml
- mlflow-networkpolicy.yaml
- mlflow-servicemonitor.yaml
- aegis-allow-metoro-to-mlflow-metrics.yaml
