apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: aegis-allow-mlflow-internal
  namespace: aegis-ml
  labels:
    app.kubernetes.io/part-of: aegis
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: mlflow
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: aegis-ml
      ports:
        - protocol: TCP
          port: 5000
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: aegis-ml
      ports:
        - protocol: TCP
          port: 5432
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: aegis-data
      ports:
        - protocol: TCP
          port: 9000
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: aegis-allow-mlflow-postgres-internal
  namespace: aegis-ml
  labels:
    app.kubernetes.io/part-of: aegis
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: mlflow-postgres
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: mlflow
      ports:
        - protocol: TCP
          port: 5432
